// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssets = `-- name: CountAssets :one
SELECT COUNT(*) FROM assets
`

func (q *Queries) CountAssets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAssets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssetsByDate = `-- name: CountAssetsByDate :one
SELECT COUNT(*) FROM assets WHERE created_at::date = $1
`

func (q *Queries) CountAssetsByDate(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countAssetsByDate, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssetsByType = `-- name: CountAssetsByType :many
SELECT type, COUNT(*)::int as count FROM assets GROUP BY type
`

type CountAssetsByTypeRow struct {
	Type  string `json:"type"`
	Count int32  `json:"count"`
}

func (q *Queries) CountAssetsByType(ctx context.Context) ([]CountAssetsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countAssetsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAssetsByTypeRow{}
	for rows.Next() {
		var i CountAssetsByTypeRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTodayAssets = `-- name: CountTodayAssets :one
SELECT COUNT(*) FROM assets WHERE created_at >= CURRENT_DATE
`

func (q *Queries) CountTodayAssets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTodayAssets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVulnsByDate = `-- name: CountVulnsByDate :one
SELECT COUNT(*) FROM assets WHERE type = 'vulnerability' AND created_at::date = $1
`

func (q *Queries) CountVulnsByDate(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countVulnsByDate, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :exec
INSERT INTO assets (id, campaign_id, type, value, source, target_id, raw_data, confidence, severity, status, lifecycle, raw_hash, source_run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateAssetParams struct {
	ID          string  `json:"id"`
	CampaignID  string  `json:"campaign_id"`
	Type        string  `json:"type"`
	Value       string  `json:"value"`
	Source      string  `json:"source"`
	TargetID    string  `json:"target_id"`
	RawData     []byte  `json:"raw_data"`
	Confidence  float64 `json:"confidence"`
	Severity    string  `json:"severity"`
	Status      string  `json:"status"`
	Lifecycle   string  `json:"lifecycle"`
	RawHash     string  `json:"raw_hash"`
	SourceRunID string  `json:"source_run_id"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) error {
	_, err := q.db.Exec(ctx, createAsset,
		arg.ID,
		arg.CampaignID,
		arg.Type,
		arg.Value,
		arg.Source,
		arg.TargetID,
		arg.RawData,
		arg.Confidence,
		arg.Severity,
		arg.Status,
		arg.Lifecycle,
		arg.RawHash,
		arg.SourceRunID,
	)
	return err
}

const deleteAssetsByCampaign = `-- name: DeleteAssetsByCampaign :exec
DELETE FROM assets WHERE campaign_id = $1
`

func (q *Queries) DeleteAssetsByCampaign(ctx context.Context, campaignID string) error {
	_, err := q.db.Exec(ctx, deleteAssetsByCampaign, campaignID)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, campaign_id, type, value, source, target_id, raw_data, confidence, severity, status, lifecycle, raw_hash, source_run_id, first_seen, last_seen, created_at
FROM assets WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Type,
		&i.Value,
		&i.Source,
		&i.TargetID,
		&i.RawData,
		&i.Confidence,
		&i.Severity,
		&i.Status,
		&i.Lifecycle,
		&i.RawHash,
		&i.SourceRunID,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, campaign_id, type, value, source, target_id, raw_data, confidence, severity, status, lifecycle, raw_hash, source_run_id, first_seen, last_seen, created_at
FROM assets
WHERE (campaign_id = $1 OR $1 = '')
  AND (type = $2 OR $2 = '')
  AND (status = $3 OR $3 = '')
  AND (source = $4 OR $4 = '')
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListAssetsParams struct {
	CampaignID string `json:"campaign_id"`
	Type       string `json:"type"`
	Status     string `json:"status"`
	Source     string `json:"source"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.CampaignID,
		arg.Type,
		arg.Status,
		arg.Source,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Type,
			&i.Value,
			&i.Source,
			&i.TargetID,
			&i.RawData,
			&i.Confidence,
			&i.Severity,
			&i.Status,
			&i.Lifecycle,
			&i.RawHash,
			&i.SourceRunID,
			&i.FirstSeen,
			&i.LastSeen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRawEvent = `-- name: SaveRawEvent :exec
INSERT INTO raw_events (id, campaign_id, artifact, target_id, target_value, target_type, workflow_id, data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SaveRawEventParams struct {
	ID          string `json:"id"`
	CampaignID  string `json:"campaign_id"`
	Artifact    string `json:"artifact"`
	TargetID    string `json:"target_id"`
	TargetValue string `json:"target_value"`
	TargetType  string `json:"target_type"`
	WorkflowID  string `json:"workflow_id"`
	Data        []byte `json:"data"`
}

func (q *Queries) SaveRawEvent(ctx context.Context, arg SaveRawEventParams) error {
	_, err := q.db.Exec(ctx, saveRawEvent,
		arg.ID,
		arg.CampaignID,
		arg.Artifact,
		arg.TargetID,
		arg.TargetValue,
		arg.TargetType,
		arg.WorkflowID,
		arg.Data,
	)
	return err
}

const updateAssetRawData = `-- name: UpdateAssetRawData :exec
UPDATE assets SET raw_data = $1 WHERE type = 'ip' AND value = $2
`

type UpdateAssetRawDataParams struct {
	RawData []byte `json:"raw_data"`
	Value   string `json:"value"`
}

func (q *Queries) UpdateAssetRawData(ctx context.Context, arg UpdateAssetRawDataParams) error {
	_, err := q.db.Exec(ctx, updateAssetRawData, arg.RawData, arg.Value)
	return err
}

const updateAssetStatus = `-- name: UpdateAssetStatus :exec
UPDATE assets SET status = $1, last_seen = NOW() WHERE id = $2
`

type UpdateAssetStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) error {
	_, err := q.db.Exec(ctx, updateAssetStatus, arg.Status, arg.ID)
	return err
}
