// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batches.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBatchRuns = `-- name: CountBatchRuns :one
SELECT COUNT(*) FROM batch_runs
`

func (q *Queries) CountBatchRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBatchRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBatchChunk = `-- name: CreateBatchChunk :exec
INSERT INTO batch_chunks (id, batch_id, target, chunk, workflow_id, status, error)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateBatchChunkParams struct {
	ID         string      `json:"id"`
	BatchID    pgtype.Text `json:"batch_id"`
	Target     string      `json:"target"`
	Chunk      string      `json:"chunk"`
	WorkflowID string      `json:"workflow_id"`
	Status     string      `json:"status"`
	Error      string      `json:"error"`
}

func (q *Queries) CreateBatchChunk(ctx context.Context, arg CreateBatchChunkParams) error {
	_, err := q.db.Exec(ctx, createBatchChunk,
		arg.ID,
		arg.BatchID,
		arg.Target,
		arg.Chunk,
		arg.WorkflowID,
		arg.Status,
		arg.Error,
	)
	return err
}

const createBatchRun = `-- name: CreateBatchRun :exec
INSERT INTO batch_runs (id, campaign_id, workflow_id, type, target, ports, status, total_chunks, completed, failed)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateBatchRunParams struct {
	ID          string `json:"id"`
	CampaignID  string `json:"campaign_id"`
	WorkflowID  string `json:"workflow_id"`
	Type        string `json:"type"`
	Target      string `json:"target"`
	Ports       string `json:"ports"`
	Status      string `json:"status"`
	TotalChunks int32  `json:"total_chunks"`
	Completed   int32  `json:"completed"`
	Failed      int32  `json:"failed"`
}

func (q *Queries) CreateBatchRun(ctx context.Context, arg CreateBatchRunParams) error {
	_, err := q.db.Exec(ctx, createBatchRun,
		arg.ID,
		arg.CampaignID,
		arg.WorkflowID,
		arg.Type,
		arg.Target,
		arg.Ports,
		arg.Status,
		arg.TotalChunks,
		arg.Completed,
		arg.Failed,
	)
	return err
}

const deleteBatchChunks = `-- name: DeleteBatchChunks :exec
DELETE FROM batch_chunks WHERE batch_id = $1
`

func (q *Queries) DeleteBatchChunks(ctx context.Context, batchID pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteBatchChunks, batchID)
	return err
}

const deleteBatchRun = `-- name: DeleteBatchRun :exec
DELETE FROM batch_runs WHERE id = $1
`

func (q *Queries) DeleteBatchRun(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBatchRun, id)
	return err
}

const getBatchChunks = `-- name: GetBatchChunks :many
SELECT id, batch_id, target, chunk, workflow_id, status, error, created_at, updated_at
FROM batch_chunks WHERE batch_id = $1 ORDER BY created_at ASC LIMIT $2 OFFSET $3
`

type GetBatchChunksParams struct {
	BatchID pgtype.Text `json:"batch_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetBatchChunks(ctx context.Context, arg GetBatchChunksParams) ([]BatchChunk, error) {
	rows, err := q.db.Query(ctx, getBatchChunks, arg.BatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchChunk{}
	for rows.Next() {
		var i BatchChunk
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Target,
			&i.Chunk,
			&i.WorkflowID,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchRun = `-- name: GetBatchRun :one
SELECT id, campaign_id, workflow_id, type, target, ports, status, total_chunks, completed, failed, created_at, updated_at
FROM batch_runs WHERE id = $1
`

func (q *Queries) GetBatchRun(ctx context.Context, id string) (BatchRun, error) {
	row := q.db.QueryRow(ctx, getBatchRun, id)
	var i BatchRun
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.WorkflowID,
		&i.Type,
		&i.Target,
		&i.Ports,
		&i.Status,
		&i.TotalChunks,
		&i.Completed,
		&i.Failed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBatchRuns = `-- name: ListBatchRuns :many
SELECT id, campaign_id, workflow_id, type, target, ports, status, total_chunks, completed, failed, created_at, updated_at
FROM batch_runs ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListBatchRunsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBatchRuns(ctx context.Context, arg ListBatchRunsParams) ([]BatchRun, error) {
	rows, err := q.db.Query(ctx, listBatchRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchRun{}
	for rows.Next() {
		var i BatchRun
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.WorkflowID,
			&i.Type,
			&i.Target,
			&i.Ports,
			&i.Status,
			&i.TotalChunks,
			&i.Completed,
			&i.Failed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBatchRunsByCampaign = `-- name: ListBatchRunsByCampaign :many
SELECT id, campaign_id, workflow_id, type, target, ports, status, total_chunks, completed, failed, created_at, updated_at
FROM batch_runs WHERE campaign_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListBatchRunsByCampaignParams struct {
	CampaignID string `json:"campaign_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListBatchRunsByCampaign(ctx context.Context, arg ListBatchRunsByCampaignParams) ([]BatchRun, error) {
	rows, err := q.db.Query(ctx, listBatchRunsByCampaign, arg.CampaignID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchRun{}
	for rows.Next() {
		var i BatchRun
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.WorkflowID,
			&i.Type,
			&i.Target,
			&i.Ports,
			&i.Status,
			&i.TotalChunks,
			&i.Completed,
			&i.Failed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatchRunStatus = `-- name: UpdateBatchRunStatus :exec
UPDATE batch_runs SET status = $1, updated_at = NOW() WHERE id = $2
`

type UpdateBatchRunStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateBatchRunStatus(ctx context.Context, arg UpdateBatchRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateBatchRunStatus, arg.Status, arg.ID)
	return err
}
