// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package dbsqlc

import (
	"context"
)

const countActiveCampaigns = `-- name: CountActiveCampaigns :one
SELECT COUNT(*) FROM campaigns WHERE status = 'active'
`

func (q *Queries) CountActiveCampaigns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCampaigns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaign = `-- name: CreateCampaign :exec
INSERT INTO campaigns (id, name, description, status, phase, phase_reason)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCampaignParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      string `json:"status"`
	Phase       string `json:"phase"`
	PhaseReason string `json:"phase_reason"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) error {
	_, err := q.db.Exec(ctx, createCampaign,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Phase,
		arg.PhaseReason,
	)
	return err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, description, status, phase, phase_reason, created_at, updated_at
FROM campaigns
WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Phase,
		&i.PhaseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, name, description, status, phase, phase_reason, created_at, updated_at
FROM campaigns
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListCampaignsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Phase,
			&i.PhaseReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :exec
UPDATE campaigns SET status = $1, updated_at = NOW() WHERE id = $2
`

type UpdateCampaignStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) error {
	_, err := q.db.Exec(ctx, updateCampaignStatus, arg.Status, arg.ID)
	return err
}
