// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActionRecord struct {
	ID         string             `json:"id"`
	CampaignID string             `json:"campaign_id"`
	Target     string             `json:"target"`
	Artifact   string             `json:"artifact"`
	Action     string             `json:"action"`
	Input      []byte             `json:"input"`
	Reason     string             `json:"reason"`
	Status     string             `json:"status"`
	WorkflowID string             `json:"workflow_id"`
	Error      string             `json:"error"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ArtifactStat struct {
	ID           string             `json:"id"`
	CampaignID   string             `json:"campaign_id"`
	WorkflowID   string             `json:"workflow_id"`
	Artifact     string             `json:"artifact"`
	Target       string             `json:"target"`
	Engine       string             `json:"engine"`
	Task         string             `json:"task"`
	Targets      int32              `json:"targets"`
	Tasks        int32              `json:"tasks"`
	Requests     int32              `json:"requests"`
	ResultsCount int32              `json:"results_count"`
	Errors       int32              `json:"errors"`
	DurationMs   int64              `json:"duration_ms"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Asset struct {
	ID          string             `json:"id"`
	CampaignID  string             `json:"campaign_id"`
	Type        string             `json:"type"`
	Value       string             `json:"value"`
	Source      string             `json:"source"`
	TargetID    string             `json:"target_id"`
	RawData     []byte             `json:"raw_data"`
	Confidence  float64            `json:"confidence"`
	Severity    string             `json:"severity"`
	Status      string             `json:"status"`
	Lifecycle   string             `json:"lifecycle"`
	RawHash     string             `json:"raw_hash"`
	SourceRunID string             `json:"source_run_id"`
	FirstSeen   pgtype.Timestamptz `json:"first_seen"`
	LastSeen    pgtype.Timestamptz `json:"last_seen"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BatchChunk struct {
	ID         string             `json:"id"`
	BatchID    pgtype.Text        `json:"batch_id"`
	Target     string             `json:"target"`
	Chunk      string             `json:"chunk"`
	WorkflowID string             `json:"workflow_id"`
	Status     string             `json:"status"`
	Error      string             `json:"error"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type BatchRun struct {
	ID          string             `json:"id"`
	CampaignID  string             `json:"campaign_id"`
	WorkflowID  string             `json:"workflow_id"`
	Type        string             `json:"type"`
	Target      string             `json:"target"`
	Ports       string             `json:"ports"`
	Status      string             `json:"status"`
	TotalChunks int32              `json:"total_chunks"`
	Completed   int32              `json:"completed"`
	Failed      int32              `json:"failed"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Campaign struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Phase       string             `json:"phase"`
	PhaseReason string             `json:"phase_reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CampaignPhaseEvent struct {
	ID         string             `json:"id"`
	CampaignID pgtype.Text        `json:"campaign_id"`
	BatchID    string             `json:"batch_id"`
	FromPhase  string             `json:"from_phase"`
	ToPhase    string             `json:"to_phase"`
	Reason     string             `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CampaignTarget struct {
	ID         string             `json:"id"`
	CampaignID pgtype.Text        `json:"campaign_id"`
	Type       string             `json:"type"`
	Value      string             `json:"value"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Policy struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Ports       string             `json:"ports"`
	Threads     int32              `json:"threads"`
	SprayDict   string             `json:"spray_dict"`
	NucleiTags  string             `json:"nuclei_tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RawEvent struct {
	ID          string             `json:"id"`
	CampaignID  string             `json:"campaign_id"`
	Artifact    string             `json:"artifact"`
	TargetID    string             `json:"target_id"`
	TargetValue string             `json:"target_value"`
	TargetType  string             `json:"target_type"`
	WorkflowID  string             `json:"workflow_id"`
	Data        []byte             `json:"data"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorkItem struct {
	ID               string             `json:"id"`
	CampaignID       string             `json:"campaign_id"`
	BatchID          string             `json:"batch_id"`
	ParentID         string             `json:"parent_id"`
	Type             string             `json:"type"`
	Target           string             `json:"target"`
	Artifact         string             `json:"artifact"`
	Queue            string             `json:"queue"`
	Input            []byte             `json:"input"`
	Schedule         string             `json:"schedule"`
	Status           string             `json:"status"`
	Attempts         int32              `json:"attempts"`
	MaxAttempts      int32              `json:"max_attempts"`
	WorkflowID       string             `json:"workflow_id"`
	Error            string             `json:"error"`
	HeartbeatStaleAt pgtype.Timestamptz `json:"heartbeat_stale_at"`
	Tail             bool               `json:"tail"`
	TailAt           pgtype.Timestamptz `json:"tail_at"`
	TailReason       string             `json:"tail_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
