// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package dbsqlc

import (
	"context"
)

const createPolicy = `-- name: CreatePolicy :exec
INSERT INTO policies (id, name, description, ports, threads, spray_dict, nuclei_tags)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePolicyParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Ports       string `json:"ports"`
	Threads     int32  `json:"threads"`
	SprayDict   string `json:"spray_dict"`
	NucleiTags  string `json:"nuclei_tags"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) error {
	_, err := q.db.Exec(ctx, createPolicy,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Ports,
		arg.Threads,
		arg.SprayDict,
		arg.NucleiTags,
	)
	return err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies
WHERE id = $1
`

func (q *Queries) DeletePolicy(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePolicy, id)
	return err
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, name, description, ports, threads, spray_dict, nuclei_tags, created_at, updated_at
FROM policies
WHERE id = $1
`

func (q *Queries) GetPolicy(ctx context.Context, id string) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicy, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Ports,
		&i.Threads,
		&i.SprayDict,
		&i.NucleiTags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, name, description, ports, threads, spray_dict, nuclei_tags, created_at, updated_at
FROM policies
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListPoliciesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPolicies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Ports,
			&i.Threads,
			&i.SprayDict,
			&i.NucleiTags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicy = `-- name: UpdatePolicy :exec
UPDATE policies
SET name = $1,
    description = $2,
    ports = $3,
    threads = $4,
    spray_dict = $5,
    nuclei_tags = $6,
    updated_at = NOW()
WHERE id = $7
`

type UpdatePolicyParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Ports       string `json:"ports"`
	Threads     int32  `json:"threads"`
	SprayDict   string `json:"spray_dict"`
	NucleiTags  string `json:"nuclei_tags"`
	ID          string `json:"id"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) error {
	_, err := q.db.Exec(ctx, updatePolicy,
		arg.Name,
		arg.Description,
		arg.Ports,
		arg.Threads,
		arg.SprayDict,
		arg.NucleiTags,
		arg.ID,
	)
	return err
}
