// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_items.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateWorkItemStatus = `-- name: BulkUpdateWorkItemStatus :exec
UPDATE work_items SET status = $1, error = $2, updated_at = NOW()
WHERE batch_id = $3 AND status IN ('pending','starting','running','retry_waiting','paused')
`

type BulkUpdateWorkItemStatusParams struct {
	Status  string `json:"status"`
	Error   string `json:"error"`
	BatchID string `json:"batch_id"`
}

func (q *Queries) BulkUpdateWorkItemStatus(ctx context.Context, arg BulkUpdateWorkItemStatusParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateWorkItemStatus, arg.Status, arg.Error, arg.BatchID)
	return err
}

const countRunningWorkItems = `-- name: CountRunningWorkItems :one
SELECT COUNT(*) FROM work_items WHERE status IN ('running','starting')
`

func (q *Queries) CountRunningWorkItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningWorkItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkItemsByStatus = `-- name: CountWorkItemsByStatus :many
SELECT status, COUNT(*)::int as count FROM work_items WHERE campaign_id = $1 AND batch_id = $2 GROUP BY status
`

type CountWorkItemsByStatusParams struct {
	CampaignID string `json:"campaign_id"`
	BatchID    string `json:"batch_id"`
}

type CountWorkItemsByStatusRow struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

func (q *Queries) CountWorkItemsByStatus(ctx context.Context, arg CountWorkItemsByStatusParams) ([]CountWorkItemsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countWorkItemsByStatus, arg.CampaignID, arg.BatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountWorkItemsByStatusRow{}
	for rows.Next() {
		var i CountWorkItemsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWorkItem = `-- name: CreateWorkItem :exec
INSERT INTO work_items (id, campaign_id, batch_id, parent_id, type, target, artifact, queue, input, schedule, status, attempts, max_attempts, workflow_id, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type CreateWorkItemParams struct {
	ID          string `json:"id"`
	CampaignID  string `json:"campaign_id"`
	BatchID     string `json:"batch_id"`
	ParentID    string `json:"parent_id"`
	Type        string `json:"type"`
	Target      string `json:"target"`
	Artifact    string `json:"artifact"`
	Queue       string `json:"queue"`
	Input       []byte `json:"input"`
	Schedule    string `json:"schedule"`
	Status      string `json:"status"`
	Attempts    int32  `json:"attempts"`
	MaxAttempts int32  `json:"max_attempts"`
	WorkflowID  string `json:"workflow_id"`
	Error       string `json:"error"`
}

func (q *Queries) CreateWorkItem(ctx context.Context, arg CreateWorkItemParams) error {
	_, err := q.db.Exec(ctx, createWorkItem,
		arg.ID,
		arg.CampaignID,
		arg.BatchID,
		arg.ParentID,
		arg.Type,
		arg.Target,
		arg.Artifact,
		arg.Queue,
		arg.Input,
		arg.Schedule,
		arg.Status,
		arg.Attempts,
		arg.MaxAttempts,
		arg.WorkflowID,
		arg.Error,
	)
	return err
}

const deleteWorkItemsByBatch = `-- name: DeleteWorkItemsByBatch :exec
DELETE FROM work_items WHERE batch_id = $1
`

func (q *Queries) DeleteWorkItemsByBatch(ctx context.Context, batchID string) error {
	_, err := q.db.Exec(ctx, deleteWorkItemsByBatch, batchID)
	return err
}

const getWorkItem = `-- name: GetWorkItem :one
SELECT id, campaign_id, batch_id, parent_id, type, target, artifact, queue, input, schedule, status, attempts, max_attempts, workflow_id, error, created_at, updated_at
FROM work_items WHERE id = $1
`

type GetWorkItemRow struct {
	ID          string             `json:"id"`
	CampaignID  string             `json:"campaign_id"`
	BatchID     string             `json:"batch_id"`
	ParentID    string             `json:"parent_id"`
	Type        string             `json:"type"`
	Target      string             `json:"target"`
	Artifact    string             `json:"artifact"`
	Queue       string             `json:"queue"`
	Input       []byte             `json:"input"`
	Schedule    string             `json:"schedule"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	WorkflowID  string             `json:"workflow_id"`
	Error       string             `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkItem(ctx context.Context, id string) (GetWorkItemRow, error) {
	row := q.db.QueryRow(ctx, getWorkItem, id)
	var i GetWorkItemRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.BatchID,
		&i.ParentID,
		&i.Type,
		&i.Target,
		&i.Artifact,
		&i.Queue,
		&i.Input,
		&i.Schedule,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.WorkflowID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkItems = `-- name: ListWorkItems :many
SELECT id, campaign_id, batch_id, parent_id, type, target, artifact, queue, input, schedule, status, attempts, max_attempts, workflow_id, error, created_at, updated_at
FROM work_items
WHERE (campaign_id = $1 OR $1 = '')
  AND (batch_id = $2 OR $2 = '')
  AND (status = $3 OR $3 = '')
  AND (type = $4 OR $4 = '')
  AND (artifact = $5 OR $5 = '')
ORDER BY updated_at DESC
LIMIT $6 OFFSET $7
`

type ListWorkItemsParams struct {
	CampaignID string `json:"campaign_id"`
	BatchID    string `json:"batch_id"`
	Status     string `json:"status"`
	Type       string `json:"type"`
	Artifact   string `json:"artifact"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type ListWorkItemsRow struct {
	ID          string             `json:"id"`
	CampaignID  string             `json:"campaign_id"`
	BatchID     string             `json:"batch_id"`
	ParentID    string             `json:"parent_id"`
	Type        string             `json:"type"`
	Target      string             `json:"target"`
	Artifact    string             `json:"artifact"`
	Queue       string             `json:"queue"`
	Input       []byte             `json:"input"`
	Schedule    string             `json:"schedule"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	WorkflowID  string             `json:"workflow_id"`
	Error       string             `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkItems(ctx context.Context, arg ListWorkItemsParams) ([]ListWorkItemsRow, error) {
	rows, err := q.db.Query(ctx, listWorkItems,
		arg.CampaignID,
		arg.BatchID,
		arg.Status,
		arg.Type,
		arg.Artifact,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkItemsRow{}
	for rows.Next() {
		var i ListWorkItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.BatchID,
			&i.ParentID,
			&i.Type,
			&i.Target,
			&i.Artifact,
			&i.Queue,
			&i.Input,
			&i.Schedule,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.WorkflowID,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
